name: Pre submits
on: [pull_request, workflow_dispatch]

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.3.4

      - name: setup-go
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.2.0
        with:
          go-version: "1.18"

      - name: Run tests for builder
        run: |
          set -euo pipefail

          # Download dependencies.
          go mod vendor
          # Build.
          go build -mod=vendor
          # Test.
          go test -mod=vendor -v ./...
