name: Pre submits
on: [pull_request, workflow_dispatch]

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.3.4

      - name: setup-go
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v2.2.0
        with:
          go-version: "1.18"

      - name: Run tests for builder
        run: |
          set -euo pipefail

          # Download dependencies.
          go mod vendor
          # Build.
          go build -mod=vendor
          # Test.
          go test -mod=vendor -v ./...
